apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: devops
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'ubuntu-wsl'
        static_configs:
          - targets: ['localhost:9100'] # Pointe vers ton Node Exporter sur WSL

      - job_name: 'jenkins'
        metrics_path: '/prometheus/'
        static_configs:
          - targets: ['172.20.198.25:8080'] # Pointe vers ton Jenkins sur Windows/WSL

      - job_name: 'spring-boot'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['localhost:8089'] # Utilise le DNS Kubernetes du service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-stack
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-storage
              mountPath: /prometheus
            - name: config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: config-volume
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: monitoring
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
      nodePort: 30091
    - name: grafana
      port: 3000
      targetPort: 3000
      nodePort: 30031